### PR TITLE
fixed progressBar bug

### PR DESCRIPTION
**Pull request by ShantelPeters**
it works well on my end

## Summary by CodeRabbit

- **New Features**
	- Enhanced the visual representation of the progress bar to accurately reflect completion based on the number of completed steps.
	- Improved styling and structure for better clarity and usability of the progress bar component.

- **Bug Fixes**
	- Simplified the rendering logic for the progress bar, ensuring a more intuitive display of milestones.

### CODE REVIEW

**Comment by ShantelPeters** [comment]
@Marchand-Nicolas kindly review

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Not working for quizzes with 4 questions, you can check on the `Account Abstraction Mastery Quiz` quest.
image

Also I think these parts should be hidden:
image

**Comment by ShantelPeters** [comment]
@Marchand-Nicolas kindly review

**Review by Marchand-Nicolas — APPROVED** [review]
Working really well! Lgtm

**Pull request merged**
