### PR TITLE
fix: to clain button

### PR DESCRIPTION
**Pull request by CollinsC1O**
Fix "To Claim" Tab Not Responding

Description:

This pull request addresses a bug where the "To Claim" tab was not responding when clicked. The issue was traced to the React Fragment (<>...</>) wrapper that was incorrectly wrapping the Tab component, which interfered with its functionality.
Pull Request Description

Changes Made:

- Removed the unnecessary React Fragment wrapper around the Tab component.
- Verified that the "To Claim" tab now responds correctly to user clicks.

Testing:

- Navigated to the "To Claim" tab and confirmed that it responds as expected.
- Checked for any regression issues related to the tab functionality.

Related Issues:

- This PR resolves the issue reported in Issue #814.

Please review and let me know if any additional changes are required.

Thanks!

## Summary by CodeRabbit

- **Improvements**
	- Enhanced readability and structure of the Quest and Collection Tabs component for better maintenance.
	- Streamlined conditional rendering for the Tab component, improving clarity without impacting functionality.

### CODE REVIEW

**Comment by CollinsC1O** [comment]
Hello @Marchand-Nicolas I've resolved the conflict you can review and merge now. Thanks

**Comment by Marchand-Nicolas** [comment]
@CollinsC1O Please do not commit pnpm-lock.yml

**Comment by CollinsC1O** [comment]
Hello @Marchand-Nicolas pnpm-lock.yml file has been removed

**Review by Marchand-Nicolas — APPROVED** [review]
LGTM Well done!

**Comment by CollinsC1O** [comment]
Thanks for the opportunity

**Pull request merged**
