### PR TITLE
test: get completed boosts api endpoint

### LINKED ISSUE #617: test: `/boost/get_completed_boosts?addr=${addr}`
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

### PR DESCRIPTION
**Pull request by mubarak23**
# Pull Request type
- Testing

Resolves: #617

### CODE REVIEW

**Comment by mubarak23** [comment]
@ayushtom see the fresh new PR, kindly review

**Comment by mubarak23** [comment]
@ayushtom share the failed deployment error logs

**Comment by ayushtom** [comment]
Screenshot 2024-05-01 at 9 01 25 PM

error logs

**Comment by mubarak23** [comment]
from what you can see, this is not part of the code, work one

**Comment by ayushtom** [comment]
This is part of the code which needs to be changed since you changed the return type of the function

**Pull request closed without merging**
