### PR TITLE
feat: add token SVG icons to public/tokens folder

### LINKED ISSUE #954: Create a `/public/tokens` folder for all Starknet yielding tokens icons
## Description 📹

Create a `/public/tokens` folder for all Starknet yielding tokens icons. I want all these tokens in SVG form[ imported from this figma
](https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=6331-10149&t=VM6Kdu04hCPgKd1U-1)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  

- [ ] Add DAI
- [ ] Add USDT
- [ ] Add USDC
- [ ] Add ETH
- [ ] Add BTC
- [ ] Add STRK
- [ ] Add WSTETH
- [ ] Add Ekubo
- [ ] Add Nostra
- [ ] Add ZEND

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by akintewe**
Description
Created `/public/tokens` folder and added SVG icons for Starknet yielding tokens as requested in issue #954.

Changes Made
- Created new `/public/tokens` directory
- Added the following token SVG icons:
  - DAI
  - USDT
  - USDC
  - ETH
  - BTC
  - STRK
  - Ekubo
  - Nostra

 Pending Items
Unable to locate the following icons in the provided Figma file:
- WSTETH
- ZEND

Testing
- Verified all SVG files are properly formatted
- Confirmed icons display correctly in local environment

Notes for Reviewer
@fricoben I was unable to find the WSTETH and ZEND icons in the Figma file. Could you please provide these assets or point me to their correct location in the Figma? Once provided, I'll update the PR with the remaining icons.

Closes #954

### CODE REVIEW

**Review by fricoben — CHANGES_REQUESTED** [review]
zend and wseth weren't in the figma ? 
- If not right delete please delete the one you put and I'll pass this PR it's our bad we'll add them later
- If yes, please include them :)

**Comment by ShantelPeters** [comment]
> zend and wseth weren't in the figma ?
> 
> * If not right delete please delete the one you put and I'll pass this PR it's our bad we'll add them later
> * If yes, please include them :)

Alright thank you

**Comment by akintewe** [comment]
> zend and wseth weren't in the figma ?
> 
> * If not right delete please delete the one you put and I'll pass this PR it's our bad we'll add them later
> * If yes, please include them :)

alright thank you, i couldn’t find them, so ill delete the ones i added :).   @fricoben

**Comment by akintewe** [comment]
please @fricoben  review

**Pull request merged**
