### PR TITLE
refactor: migrate manual api calls to api.service (fixes #526)

### LINKED ISSUE #526: Replace manual fetch calls with a common function
We make many api calls throughout the app and often times we call the same endpoint on multiple pages. Using the same fetch call again and again by manually pasting the whole string url can be quite time taking if we are just reusing the same long code in multiple places. This also means that if we ever want to upgrade this url, we will have to manually change it in all the places we used the endpoint.

To solve this, we have started to make these api calls in a function of their own with an appropriate name which we call when we want to make that api call.We have a folder called `services` which contains the `apiService.ts` file. This file contains some functions which are used throughout the app and we try to make an active effort to use these functions only. Any new api call will get it's function defined here and we will call that function if we want to make that api call.

In some places in the app like [this](https://github.com/starknet-id/starknet.quest/blob/ayush/analytics/app/achievements/page.tsx#L34) we see that we have placed a fetch call. Your mission in this task would be to give all such endpoints it's respective function inside the `apiService.ts` file and replace the fetch call with the function you created. We have some functions already which we use  so you also you can see through it and start doing them for the other endpoints. This also means that you will have to carefully test if all the calls which you replaced are working as expected and also make sure you use the correct url when making this function. 

Remember one thing, 
Naming variables/functions is one of the most difficult things in software engineering as the name which you give has to mean the same for everyone who will go through your code to build on it so take your time to think and implement this for all endpoints and i am certain by the end of this you will have a good walkthrough of our codebase too

### PR DESCRIPTION
**Pull request by him2312**
## Summary
Migrates all manual API calls to `api.service` file. Fixes #526 

### Changelog

- [x] Deprecate `questService.ts` and move `getQuestById`, `fetchQuestCategoryData` to `apiService.ts`

#### page/achievements
- [x] `getUserAchievementByCategory`
- [x] `getUserAchievements`
- [x] `verifyUserAchievement`

#### page/quest/[id]
- [x] `fetchQuestData`
- [x] `getTasksByQuestId`
- [x] `getEligibleRewards`

#### Land
- [x] `fetchBuildings`

#### Quiz
- [ ] `getQuizById` (couldn’t test due to lack of Starknet domain)

#### useCreationDate
- [x] `getDeployedTimeByAddress`

### CODE REVIEW

**Comment by ayushtom** [comment]
can you resolve the build issue here? @him2312 
I would need to test it end to end after build is created

**Comment by him2312** [comment]
> can you resolve the build issue here? @him2312 I would need to test it end to end after build is created

@ayushtom sorry but I don't have access to Vercel build logs.
From local `pnpm build` logs I could see 2 issues
- `@mui/material-icons` didn't have `Wallet` being exported. Updated the package version here.
- Changed `types/backend` instead of `@types/backend`.

Screenshot 2024-03-12 at 9 20 35 AM

**Comment by ayushtom** [comment]
I resolved the suggestion pointed out by you here https://github.com/starknet-id/starknet.quest/pull/518#discussion_r1518571898 in #530

**Comment by ayushtom** [comment]
can you resolve build error @him2312

**Review by ayushtom — APPROVED** [review]
lgtm

**Pull request merged**
