### PR TITLE
Fix: add defi concept cards below the table

### LINKED ISSUE #956: Essential DeFi Concepts Section
## Description 📹

**We've added a new section to the DeFi page, located below the table section. This section is designed to help users understand specific DeFi concepts through simple, easy-to-read cards.**

Current page : https://starknet.quest/discover/defi
Design link : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=6356-1377&t=9Ky1zTkRkLF10uV9-1

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  

- [ ] Create a `Card.tsx` component for each glossary element (without installing new dependencies)
- [ ] Use a similar architecture than this to use your Card component https://v0.dev/chat/B0eTJshQO61?b=b_jRkGxYcCcQD&p=0

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by omsant02**
Fix: add defi concept cards below the table

Description 📹
Added a new section to the DeFi page, located below the table section. This section helps users understand specific DeFi concepts through simple, easy-to-read cards.

Changes Made:
- Created DeFiConceptCard component for displaying concept cards
- Added grid layout for responsive display
- Implemented 12 DeFi concept cards with icons and descriptions
- Added proper styling to match the Figma design
- Organized constants in a separate file for better maintainability

Testing:
- Verified responsive layout works on all screen sizes
- Confirmed styles match the provided design
- Tested with different content lengths
- Ensured proper alignment with the table above

Close #956

image

## Summary by CodeRabbit

- **New Features**
	- Introduced a new section displaying essential DeFi concepts with visually distinct cards.
	- Added a new `DeFiConceptCard` component to enhance the presentation of DeFi concepts.
	- Included a constant `DEFI_CONCEPTS` to define various DeFi concepts with titles, descriptions, and icons.
	- Added multiple new icons representing various DeFi concepts, improving visual representation.

- **Bug Fixes**
	- No specific bug fixes were noted in this release.

- **Documentation**
	- Updated internal documentation to reflect the new DeFi concepts and component usage.

### CODE REVIEW

**Review by fricoben — CHANGES_REQUESTED** [review]
AI comments + front-end not building

**Comment by omsant02** [comment]
hi @fricoben 
made the fixes, please review
Thank you

**Review by fricoben — CHANGES_REQUESTED** [review]
- [ ] Icons are not corresponding to the figma icons 
- [ ] Padding at the end is not big enough
- [ ] "Essential deFi concepts" title isn't in the right size and weigh, please use a standardize title

**Comment by omsant02** [comment]
done 👍 @fricoben ,

please review it,

Thank you

**Review by fricoben — CHANGES_REQUESTED** [review]
responsive doesn't work.

Capture d’écran 2024-11-25 à 09 02 24

Please be sure to test before sending a PR !

**Comment by omsant02** [comment]
hi @fricoben 
i am extremely sorry for raising the pr without checking,
i have made the changes
image
image
image
image


are we good to go?

**Comment by fricoben** [comment]
> hi @fricoben i am extremely sorry for raising the pr without checking, i have made the changes image image image image
> 
> are we good to go?

No you didn't push^^

**Comment by omsant02** [comment]
> > hi @fricoben i am extremely sorry for raising the pr without checking, i have made the changes image image image image
> > 
> > are we good to go?
> 
> No you didn't push^^

Yeah, I just wanna make sure if everythings fine then I'll push 

Or if any changes to be made, then I'll update and then I'll push
Thats what I was thinking

**Comment by omsant02** [comment]
@fricoben 
i have pushed and everything's looking fine,
please review

thank you

**Review by fricoben — APPROVED** [review]
lgtm

**Pull request merged**
