### PR TITLE
feat: add Dropdown component with customizable styles

### LINKED ISSUE #697: Dropdown Component
refer https://github.com/starknet-id/starknet.quest/issues/693

### PR DESCRIPTION
**Pull request by jimenezz22**
# Pull Request type

- Feature: @ayushtom This PR adds a new Dropdown component to `components/UI/dropdown.tsx` for displaying a dropdown with customizable styles.
- Resolves: #697 

## Other information

- Supports custom styles 

- Dropdown looks like:

dropdown_1
dropdown_2

## Summary by CodeRabbit

- **New Features**
  - Introduced a customizable dropdown menu component, allowing users to select options from a list.
  - Added support for styling customization, including background color, border color, and text color for the dropdown menu and its items.

### CODE REVIEW

**Comment by ayushtom** [comment]
hey
i think the dropdown image which you posted is not looking like this
Can you please look into this?

Screenshot 2024-05-28 at 4 24 11 PM

**Comment by jimenezz22** [comment]
@ayushtom This is how it looks now, the borders, width, arrow icon and other minor style characteristics have been modified. Now it looks the same as the figma design.

dropdown2

dropdown1

**Comment by ayushtom** [comment]
@jimenezz22 i think the arror is sticking to the right side of the container here. Can you add similar padding which is there in the figma file

**Comment by jimenezz22** [comment]
@ayushtom padding style added for the arror

image

**Review by ayushtom — COMMENTED** [review]
lgtm

**Review by ayushtom — APPROVED** [review]

**Pull request merged**
