### PR TITLE
feat: added tests for getQuestbyId api endpoint

### LINKED ISSUE #610: test: `/get_quest?id=${questId}`
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

### PR DESCRIPTION
**Pull request by krshishir1**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

Resolves: #610

## Other Information

Added 3/4 tests. For the fourth test ie; for endpoint ( that does not have id query parameter)
```
Eg: https://sepolia.api.starknet.quest/get_quest
Returns error message: Failed to deserialize query string: missing field `id`
```

We need to make changes in apiService.ts file
```diff
- const response = await fetch(`${baseurl}/get_quest?id=${questId}`);
  if(!response.ok) {
    return await response.text()
  }
  const data: QuestDocument | QueryError = await response.json();
  return data as QuestDocument;
```

### CODE REVIEW

**Comment by ayushtom** [comment]
can you please resolve conflicts?

**Comment by krshishir1** [comment]
@ayushtom could you review this.

**Comment by ayushtom** [comment]
@krshishir1 can you handle the 4th test case too and instead of returning a text , make this code inside a try catch and handle the error case in the catch block

**Comment by ayushtom** [comment]
@krshishir1 i will be assigning someone else to finish this PR today. If you can then please commit the changes here so i can review and merge or else we give it to someone who can close the issue

**Comment by Ugo-X** [comment]
can i take this?

**Comment by Oshioke-Salaki** [comment]
can i

**Comment by saimeunt** [comment]
Hey I'd like to finish this one please @ayushtom

**Pull request merged**
