### PR TITLE
feat: empty claim state

### LINKED ISSUE #722: Empty 'To Claim' Quest View section
Figma : https://www.figma.com/design/fh0OAvj4AS08kHoSxu3DkE/%F0%9F%9A%80-Starknet-Quest?node-id=5409-29116&t=siYIjELkI3CzUjfH-1

### PR DESCRIPTION
**Pull request by estherbreath**
# Pull Request type

Empty claim state

Please add the labels corresponding to the type of changes your PR introduces:
- Feature

Resolves: #722

## Summary by CodeRabbit

- **New Features**
  - Added a message and image display when there are no claimable quests on the home page.

- **Refactor**
  - Updated styles and classNames for "Boosts Quest" components for improved readability and consistency.

- **Bug Fixes**
  - Enhanced rendering logic to handle empty states for claimable quests more gracefully.

### CODE REVIEW

**Comment by ayushtom** [comment]
Screenshot 2024-07-02 at 11 19 39 AM
Screenshot 2024-07-02 at 11 20 31 AM



the styling in the first image needs to be followed. I dont think the one you coded looks like the expected output. Can you please check this?

**Comment by estherbreath** [comment]
It has been updated, Boss

**Review by fricoben — CHANGES_REQUESTED** [review]
## Last change

Capture d’écran 2024-07-29 à 17 39 18

Text should have a better display on mobile (horizontal margins)

**Comment by fricoben** [comment]
Too much time in the PR I replaced it by #788

**Pull request closed without merging**
