### PR TITLE
test: get completed boosts api endpoint

### PR DESCRIPTION
**Pull request by leevigh**
I rewrote the test cases for getCompletedBoosts because it wasn't in the code when I pulled it from the testnet branch. I also reproduced the build error and fixed it.

# Pull Request type
Testing, Bugfix

Please add the labels corresponding to the type of changes your PR introduces: Bugfix, testing

- Bugfix
- Feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)
- Build-related changes
- Documentation content changes
- Testing
- Other (please describe):

Resolves: #NA

### CODE REVIEW

**Comment by ayushtom** [comment]
Hey @leevigh 
The branch I mention in the issue has the the test cases you are looking for. Can you add those by cherry picking the commits ?

**Comment by leevigh** [comment]
> Hey @leevigh The branch I mention in the issue has the the test cases you are looking for. Can you add those by cherry picking the commits ?

I've cherry picked the commits and added the tests from it, please review @ayushtom

**Comment by ayushtom** [comment]
@leevigh i would need you to cherry pick commits and push them first and then push your changes so that the contributor is added as a participant on the PR. 

Something like this - https://github.com/starknet-id/starknet.quest/pull/657

**Comment by leevigh** [comment]
> @leevigh i would need you to cherry pick commits and push them first and then push your changes so that the contributor is added as a participant on the PR.
> 
> Something like this - #657

Hi @ayushtom, I have cherry-picked the commits from the previous contributor and it's now included as a participant and also made some changes to their test case that was failing. Please review, thanks.

**Review by ayushtom — APPROVED** [review]
lgtm

**Pull request merged**
