### PR TITLE
add test case for getQuizById

### LINKED ISSUE #609: test: `/get_quiz?id=${quizId}&addr=${address}`
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

### PR DESCRIPTION
**Pull request by saimeunt**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

Resolves: #609 

## Other information

My issue covers line 228 - 238

Screenshot 2024-04-25 at 15 34 56

### CODE REVIEW

**Review by ayushtom — COMMENTED** [review]
can you add the return type in the api call so that we can access those typings on the front

**Comment by saimeunt** [comment]
@ayushtom I've added typings for `getQuizById` as requested:

https://github.com/starknet-id/starknet.quest/pull/644/files#diff-b493c7b546276bbc62ba53716aaced9d3984a8f5ccf6033b1da8e378a37acfa8R232

**Comment by ayushtom** [comment]
@saimeunt your test cases are failing

**Comment by saimeunt** [comment]
@ayushtom Sorry about that, it should pass now.

**Review by ayushtom — APPROVED** [review]
lgtm

**Pull request merged**
