### PR TITLE
test: get user achievements function

### LINKED ISSUE #773: Testing Functions in @services/apiService 1
# Issue: Testing Functions in @services/apiService

## Description

We have identified several functions within our `@services/apiService` that are defined but not imported in the main service file. To ensure these functions are working correctly and to improve our test coverage, we need to create tests for them. Here is a list of the functions that require testing:

1. `getUserAchievements`
2. `getUserAchievementByCategory`

## Testing Strategy

The overall logic for testing these functions will follow a pattern similar to the existing tests in our codebase. The key points to focus on include:

1. **Mocking the `fetch` Call**:
    - Use `jest.fn()` to mock the `fetch` global method.
    - Ensure `fetch` is reset before each test to avoid interference between tests.

2. **Simulating API Responses**:
    - Mock the responses returned by the `fetch` call for both successful and error cases.
    - Test different response formats to ensure robustness.

3. **Validating API Calls**:
    - Use `expect` to assert that `fetch` was called with the correct URL and parameters.
    - Check that the returned data matches the expected output.

4. **Handling Edge Cases**:
    - Test for null, undefined, and other edge cases in the function parameters.
    - Ensure the functions handle API errors gracefully.

## Example Test Case Structure

Here's a brief outline of what a test case might look like for one of the functions:

```javascript
describe("getUserAchievements function", () => {
  beforeEach(() => {
    fetch.mockClear();
  });

  it("should fetch and return data for a valid address", async () => {
    const mockData = [/* mock data */];
    fetch.mockResolvedValueOnce({
      json: () => Promise.resolve(mockData),
    });

    const result = await getUserAchievements("valid-address");
    expect(fetch).toHaveBeenCalledWith(
      `${API_URL}/achievements/fetch?addr=valid-address`
    );
    expect(result).toEqual(mockData);
  });

  it("should handle fetch errors gracefully", async () => {
    const mockResponse = "Error fetching achievements";
    fetch.mockResolvedValueOnce({
      json: () => Promise.reject(mockResponse),
    });

    const result = await getUserAchievements("invalid-address");
    expect(fetch).toHaveBeenCalledWith(
      `${API_URL}/achievements/fetch?addr=invalid-address`
    );
    expect(result).toBeUndefined();
  });

  // Add more tests for edge cases and different response formats
});
```

## Tasks

- [ ] Create test cases for `getUserAchievements`
- [ ] Create test cases for `getUserAchievementByCategory`

By following the above strategy, we can ensure that all the functions are thoroughly tested and any potential issues are identified early.

### PR DESCRIPTION
**Pull request by NueloSE**
# test

Please add the labels corresponding to the type of changes your PR introduces:

- Testing

Resolves: #773

## Summary by CodeRabbit

- **Bug Fixes**
	- Removed the `getUserAchievementByCategory` function, streamlining the API's approach to user achievements.

- **Tests**
	- Introduced a comprehensive test suite for the `getUserAchievements` functionality, validating various scenarios such as successful data retrieval and handling of invalid formats.
	- Enhanced test coverage ensures the function performs correctly in different situations and edge cases.

### CODE REVIEW

**Comment by NueloSE** [comment]
Hello @fricoben i have been unable to make any calls to the api for getUserAchievementByCategory. Can i get some aassistance on this??
This is the current forma I am using "https://sepolia.api.starknet.quest/achievements/Argent Explorer NFT?addr=0&category_id=1" and i get a 404 error

**Comment by fricoben** [comment]
> Hello @fricoben i have been unable to make any calls to the api for getUserAchievementByCategory. Can i get some aassistance on this?? This is the current forma I am using "https://sepolia.api.starknet.quest/achievements/Argent Explorer NFT?addr=0&category_id=1" and i get a 404 error

checking with the back-end team and I'll comeback to you

**Comment by fricoben** [comment]
> Hello @fricoben i have been unable to make any calls to the api for getUserAchievementByCategory. Can i get some aassistance on this?? This is the current forma I am using "https://sepolia.api.starknet.quest/achievements/Argent Explorer NFT?addr=0&category_id=1" and i get a 404 error

As said on Telegram, the `getUserAchievementByCategory` function doesn't work anymore so you can delete it from the test and from the code (we don't use it anywhere)

**Review by fricoben — APPROVED** [review]
lgtm

**Pull request merged**
