### PR TITLE
fix: To Claim Button

### PR DESCRIPTION
**Pull request by CollinsC1O**
Fix "To Claim" Tab Not Responding

Description:

This pull request addresses a bug where the "To Claim" tab was not responding when clicked. The issue was traced to the React Fragment (<>...</>) wrapper that was incorrectly wrapping the Tab component, which interfered with its functionality.
Pull Request Description

Changes Made:

    Removed the unnecessary React Fragment wrapper around the Tab component.
    Verified that the "To Claim" tab now responds correctly to user clicks.

Testing:

    Navigated to the "To Claim" tab and confirmed that it responds as expected.
    Checked for any regression issues related to the tab functionality.

Related Issues:

    This PR resolves the issue reported in Issue 

    Option " To claim " is not working properly for Boost Quest's  #814.

Please review and let me know if any additional changes are required.

Thanks!

### CODE REVIEW

**Comment by CollinsC1O** [comment]
Hi @revengexd  did love you check my PR out. Please review and let me know if any additional changes are required.

**Review by Marchand-Nicolas — APPROVED** [review]
ReVeNgeXD confirmed me it worked. Also the code is clean. Lgtm!

**Comment by Marchand-Nicolas** [comment]
Could you resolve the conflicts please @CollinsC1O so that I can merge

**Comment by CollinsC1O** [comment]
ok let me do that right away

**Comment by CollinsC1O** [comment]
OK I will do that right away

**Pull request closed without merging**
