### PR TITLE
Fix: Refactor QuestBanner to use banner object instead of questId

### LINKED ISSUE #986: Update `components/quests/questBanner.tsx` to no longer use JSON
## Description 📹

**Update `components/quests/questBanner.tsx` to no longer use a JSON file (`questbanners.json`) and instead rely on a `banner` object passed as a prop. Update `questDetails.tsx` to replace `<QuestBanner questId={questId} />` with `<QuestBanner banner={quest.banner} />`.**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  

   Update `QuestBanner` to use a `banner` object instead of looking up the JSON file:
   - Update the props for the `QuestBanner` component to accept a `banner` object instead of `questId`.
   - Remove references to `useMemo` and the `questBanners` JSON file.
   - Adjust the JSX to use the fields from the `banner` prop directly.

   Update the `questDetails.tsx` file:
   - Replace `<QuestBanner questId={questId} />` with `<QuestBanner banner={quest.banner} />`.

   Updated code snippets:

   **`components/quests/questBanner.tsx`:**
   ```tsx
   import { FunctionComponent } from "react";
   import styles from "@styles/quests.module.css";
   import Button from "@components/UI/button";

   type Banner = {
     image: string;
     tag?: string;
     title: string;
     description: string;
     href: string;
     cta: string;
   };

   type QuestBannerProps = {
     banner: Banner;
   };

   const QuestBanner: FunctionComponent<QuestBannerProps> = ({ banner }) => {
     return (
       <div className={styles.questBanner}>
         <div
           className={styles.questBannerImage}
           style={{ backgroundImage: `url(${banner.image})` }}
         />
         <div className={styles.questBannerContent}>
           <h2 className={styles.questBannerTitle}>
             {banner.tag ? (
               <span className={styles.bannerTag}>{banner.tag} - </span>
             ) : null}
             {banner.title}
           </h2>
           <p>{banner.description}</p>
           <div className="w-fit">
             <Button
               onClick={() => {
                 window.open(banner.href, "_blank");
               }}
             >
               {banner.cta}
             </Button>
           </div>
         </div>
       </div>
     );
   };

   export default QuestBanner;
   ```

   **`components/quests/questDetails.tsx`:**
   ```tsx
   import QuestBanner from "./questBanner";

   // Existing code...

   return (
     <div>
       {/* Replace questId with quest.banner */}
       <QuestBanner banner={quest.banner} />
     </div>
   );
   ```

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   
   ```bash
   git commit -m "Fix: Refactor QuestBanner to use banner object instead of questId"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by KeneePatel**
# Fix

Please add the labels corresponding to the type of changes your PR introduces:

- Feature
- Refactoring

Resolves: #986 

## Other information

- Added a type in `backType.ts` for Banner, and changed line position of few attributes for readability
- Updated QuestDocument type to have an optional banner attribute
- Updated QuestBanner to use banner object instead of questId
- Removed the json file from public folder

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `Banner` prop in the `QuestBanner` component, enhancing the display of quest-related information.
	- Conditional rendering of the `QuestBanner` based on the presence of a valid banner.

- **Enhancements**
	- Expanded the `QuestDefault` structure to include a new `banner` object with relevant details.
	- Updated the `QuestDocument` type to include new properties for additional descriptions and a banner.

- **Bug Fixes**
	- Removed reliance on static JSON for banner details, simplifying the component structure.

- **Chores**
	- Deleted the obsolete `questbanners.json` file.

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Working really well, gg!
Please remove package-lock.json from the PR

**Comment by KeneePatel** [comment]
> Working really well, gg! Please remove package-lock.json from the PR

Removed ❎

**Review by Marchand-Nicolas — APPROVED** [review]
Lgtm!

**Comment by KeneePatel** [comment]
@all-contributors please add @KeneePatel for code

**Pull request merged**
