### PR TITLE
refac: Implement color from tailwind config throughout the app (fixes #525)

### LINKED ISSUE #525: Implement color from tailwind config throughout the app
We have defined a certain set of color codes in the `globals.css` file which will be used throughout the app. refer [here](https://github.com/starknet-id/starknet.quest/blob/ayush/analytics/styles/globals.css#L22)

We avoid using any other colors to keep the design consistent throughout the app. In some places in the codebase , although the colors used are the same , we have added the hex codes manually and don't use css variables to use these colors directly from the `globals.css` file.

An example of using colors from the global file using css variable can be found [here](https://github.com/starknet-id/starknet.quest/blob/ayush/analytics/styles/leaderboard.module.css#L143)

Your mission is to rectify all these places throughout the css files and replace them with their respective css variable. If there's any color which is being used more than 2-3 times and isn't defined in the global file, do let us know and we can define it in the global file so that it can be used throughout the app. All the best!

**Estimated time:** 20-30 minutes

### PR DESCRIPTION
**Pull request by manoahLinks**
repeated colors without css variables

#070708
#a6a5a7
#fff 
#AAB1B6

### CODE REVIEW

**Comment by him2312** [comment]
Hey @manoahLinks .

For future reference - update the PR name/commit so that it links to the issue (#525 in this case) ?
It will be easier to track. Thank you.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by manoahLinks** [comment]
just updated the name, thanks

**Comment by ayushtom** [comment]
@manoahLinks 
you can rename the colors in the global.css file like below - 
#fff - white
#a6a5a7 - textGray

Otherwise code lgtm

**Comment by manoahLinks** [comment]
done

**Review by ayushtom — APPROVED** [review]
lgtm

**Pull request merged**
