### PR TITLE
Fix: Remove footer from the home page

### LINKED ISSUE #972: Remove the footer from the home page
## Description 📹

**Remove the footer from the home page**

Link : https://starknet.quest/

Screenshot 2024-12-03 at 14 31 58

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by SimplementeCao**
# Remove footer from the home page

## Description

Separate the `metadata` and `viewport` settings in a separate file `metadata.ts` inside the app folder, for Next.js compatibility. Also, adjust the `layout.tsx` to export these settings and mark it as a client component using `“use client”`. To be able to use `usePathname` and show the footer only in paths other than the main page (“/”).

Please add the labels corresponding to the type of changes your PR introduces:

- Refactoring (no functional changes, no API changes)

Resolves: #972 

## Files Changed:

Add `metadata.tsx`
Refactor `layout.tsx`

## Updated website
Screenshot from 2024-12-19 19-07-46

# Defi
image

# Quest
image

## Summary by CodeRabbit

- **New Features**
	- Introduced centralized metadata and viewport settings for improved social media integration and user experience.
	- Added conditional rendering for the `Footer` component based on the current pathname.

- **Bug Fixes**
	- Removed outdated metadata and viewport exports to streamline layout functionality.

### CODE REVIEW

**Comment by SimplementeCao** [comment]
@Marchand-Nicolas one question, is it necessary to remove the component as well?

**Comment by Marchand-Nicolas** [comment]
> @Marchand-Nicolas one question, is it necessary to remove the component as well?

**Comment by Marchand-Nicolas** [comment]
> @Marchand-Nicolas one question, is it necessary to remove the component as well?

I see you removed the footer from all pages. We don't want that. Only remove it from the homepage

**Comment by SimplementeCao** [comment]
I have already made the changes!

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect lgtm!

**Pull request merged**
