### PR TITLE
MEP 21/04/2024

### PR DESCRIPTION
**Pull request by ayushtom**

### CODE REVIEW

**Comment by Xaxxoo** [comment]
Hi @ayushtom I think there is a mix up here or something.

**Comment by ayushtom** [comment]
> Hi @ayushtom I think there is a mix up here or something.

hey what's the issue?

**Comment by Xaxxoo** [comment]
I think you assigned me an issue that's already been done and skipped the part where I asked for an issue. Mix up I think.

**Comment by ayushtom** [comment]
> I think you assigned me an issue that's already been done and skipped the part where I asked for an issue. Mix up I think.

can you mention the issue here so i can assign the issue to you?

**Comment by Xaxxoo** [comment]
> > I think you assigned me an issue that's already been done and skipped the part where I asked for an issue. Mix up I think.
> 
> can you mention the issue here so i can assign the issue to you?

https://github.com/starknet-id/starknet.quest/issues/602#issuecomment-2068857302

**Pull request merged**
