### PR TITLE
Add custom typography component

### LINKED ISSUE #694: Typography component
refer #693

### PR DESCRIPTION
**Pull request by lindsaymoralesb**
# Pull Request type

Please add the labels corresponding to the type of changes your PR introduces:

- Feature

Resolves: #694

## Other information

- Proof of component testing:

Code:
Screenshot 2024-05-25 at 16 34 21

How it looks on the website:
Screenshot 2024-05-25 at 16 35 14

- Also added documentation for the component for future reference when integrating, so when hovering or using the component the developer will have access to a small example on how to use it correctly.
Screenshot 2024-05-25 at 16 34 07

## Summary by CodeRabbit

- **New Features**
  - Introduced a `Typography` component for consistent text styling across the application.

- **Refactor**
  - Replaced various `<p>`, `<h1>`, `<h2>`, and `<h3>` elements with the new `Typography` component for improved styling consistency.

- **Style**
  - Updated multiple CSS files to remove redundant color properties, enhancing the centralized control of text colors and styles.

These changes enhance the visual consistency and maintainability of text elements throughout the application.

### CODE REVIEW

**Review by ayushtom — COMMENTED** [review]
Good job! The code is really well done and i dont think there's anything to refactor here.
Just one thing - remove `font-style:normal` since it make any changes to our current component

Can you also replace these stylings across the app so the app is using this component in production as soon as we merge?

**Comment by lindsaymoralesb** [comment]
Thanks! I'm glad it's what you expected 🙌🏻
Sure! I'll work on that and let you know once it's done.

**Comment by lindsaymoralesb** [comment]
Hey @ayushtom
I have a question... you asked me to replace the typography component throughout the project. Question is: whenever i find a h1 tag in the project for example, should I use the typography H1 type even if the new styles doesn't match the ones that the tag is currently using?

**Comment by ayushtom** [comment]
> Hey @ayushtom I have a question... you asked me to replace the typography component throughout the project. Question is: whenever i find a h1 tag in the project for example, should I use the typography H1 type even if the new styles doesn't match the ones that the tag is currently using?

i think if it's a recurring font style then you can modify your h1style to match with the current styling. And if it's only for one instance then adding custom styling should be good for that tag only

**Comment by lindsaymoralesb** [comment]
Hey! @ayushtom I replace the new Typography component for all the headings and p tags on the project. Also, for the ones that didn't have any style, I used the new body_default, lmk if that's ok or if I should remove that.
Apart from that, PR is ready for review. Let me know if I'm missing any texts.

**Review by ayushtom — APPROVED** [review]
lgtm

**Pull request merged**
