### PR TITLE
test: /boost/get_quests?boost_id=${id}

### LINKED ISSUE #614: test: `/boost/get_quests?boost_id=${id}`
read description here - https://github.com/starknet-id/starknet.quest/issues/602#issue-2255907921

### PR DESCRIPTION
**Pull request by lindsaymoralesb**
# Pull Request type

- Testing

Resolves: #614 

# Other information

Screenshot 2024-04-27 at 12 47 01

### CODE REVIEW

**Review by ayushtom — APPROVED** [review]
lgtm

**Comment by ayushtom** [comment]
@lindsaymoralesb your build is failing

**Review by ayushtom — CHANGES_REQUESTED** [review]
fix build issue so we can merge

**Comment by lindsaymoralesb** [comment]
@ayushtom Done!

**Review by ayushtom — APPROVED** [review]
lgtm

**Pull request merged**
